### ISSUE TITLE
Icon doesn't show

### ISSUE THREAD

**Issue by mwakaambrose** [bastidest/vue-step-progress#1]
I have used the lib in a laravel 5.7 project and when I go  to the next step, tick icon doesn't show

**Comment by bastidest** [comment]
Thank you for your interest in this library, I recently discovered a similar library that is well-tested and does virtually the same thing (and many more) after a bit of modification. [vue-form-wizard](https://github.com/BinarCode/vue-form-wizard)

If you still want to use this library, can you send me a screenshot of the broken tick icon/the progress stepper?

**Comment by mwakaambrose** [comment]
@bastidest here is the screenshot

![screenshot from 2018-10-07 19-54-43](https://user-images.githubusercontent.com/8328295/46860940-1c0ebe80-ce1a-11e8-8328-8ebd94845812.png)

**Comment by bastidest** [comment]
#2 should fix this issue

Sorry that it took so long, but it should be fixed now. Please update to version 0.2.0 and check if it works for you.
