### ISSUE TITLE
SSR not working with Nuxt: Self is not defined

### ISSUE THREAD

**Issue by MuizU** [bastidest/vue-step-progress#14]
![image](https://user-images.githubusercontent.com/35157872/110136552-d3466e80-7df5-11eb-8b3c-bceb1cc9b546.png)
I get the error displayed above for the code I have below
```
<template>
	<div class="body">
		<step-progress :steps="steps" :current-step="currentStep">
		</step-progress>
	</div>
</template>

<script>
import StepProgress from "vue-step-progress";
import "vue-step-progress/dist/main.css";
export default {
	components: {
		"step-progress": StepProgress,
	},
	data: function () {
		return {
			steps: ["Step 1", "Step 2", "Step 3"],
			currentStep: 1,
		};
	},
};
</script>

```

**Comment by bastidest** [comment]
Thanks for reporting an issue! 

I don't have enough information to reproduce your error. Can you provide a [Minimal, Reproducible Example ](https://stackoverflow.com/help/minimal-reproducible-example) via [jsfiddle](https://jsfiddle.net/) or a similar service?

**Comment by MuizU** [comment]
https://codepen.io/muizu/pen/VwmBovv

**Comment by MuizU** [comment]
Here is a sandbox link it works better
https://codesandbox.io/s/strange-fog-0zm7f?file=/pages/index.vue

**Comment by bastidest** [comment]
If you disable Server Side Rendering (SSR) in the `nuxt.config.js`, the issue disappears:
```
ssr: false,
```

It looks like SSR causes this issue. I did not explicitly implement or enable SSR, nor do I know what has to be done to enable that. I am happy to accept PRs for implementing this. I'm not planning on doing it myself tho.

**Comment by MuizU** [comment]
> If you disable Server Side Rendering (SSR) in the `nuxt.config.js`, the issue disappears:
> 
> ```
> ssr: false,
> ```
> 
> It looks like SSR causes this issue. I did not explicitly implement or enable SSR, nor do I know what has to be done to enable that. I am happy to accept PRs for implementing this. I'm not planning on doing it myself tho.

Thank you it worked
