### ISSUE TITLE
How can i add button?

### ISSUE THREAD

**Issue by cmrktmr** [bastidest/vue-step-progress#15]
How can i add button for next step?

**Comment by bastidest** [comment]
Hi, please have a look at the provided example. The easiest way is to increment a variable assigned to the `current-step` prop:

https://github.com/bastidest/vue-step-progress/blob/74a77821a03cbf1565dbb764984df912b0777b05/dev/App.vue#L4-L19

**Comment by cmrktmr** [comment]
Hi thank you for interest but im new on vue.js.  

Now Im using this,
```
<div>
  <step-progress :steps="mySteps" :current-step="currentStep" icon-class="fa fa-check"></step-progress>
</div>
```
And i added mystep array on data. I have a 4 step. Do I need to add for Methods for currentStep++ ?

**Comment by cmrktmr** [comment]
Oky i solve it 👍  but how can i make it smaller circle?

**Comment by bastidest** [comment]
The style can be customized by adjusting the appropriate CSS classes.

https://github.com/bastidest/vue-step-progress/blob/74a77821a03cbf1565dbb764984df912b0777b05/src/StepProgress.vue#L88
