### ISSUE TITLE
Steps not rendering in Production build

### ISSUE THREAD

**Issue by romanmartushev** [bastidest/vue-step-progress#20]
When I pulled this new release in (v1.0.0) the steps are not rendering. Getting error `Invalid VNode type: Symbol() (symbol) `. By the looks of it this means there are multiple instances of Vue are being pulled in. However when developing this release it had no issue rendering in dev.

**Comment by bastidest** [comment]
I'll take a look at it. I will create a dev-server that serves the prebuilt files.

**Comment by bastidest** [comment]
Looks like I accidentally bundled vue in the production build. It is now included as external.

Relevant Changes: https://github.com/bastidest/vue-step-progress/commit/8ea63f2e794f174b02bda7fac2c069ed47c701c7

I created a new release for you to test: https://www.npmjs.com/package/vue-step-progress/v/1.0.1-rc1

**Comment by romanmartushev** [comment]
that fixed the issue! Thanks for the fast reply and fix!
