### ISSUE TITLE
Could not resolve "Vue" on deploy (linux or any case sensitive operational systems.

### ISSUE THREAD

**Issue by capoia** [bastidest/vue-step-progress#21]
Hello, first i need to thank you for this package. 
I'm using your package but I'm having some problems when I go up to production!
I'm using it on nuxt3 and on my notebook (macbook air m1) it works fine, but in production it generates an error!
From what I've seen it's because of the case sensitive, 'Vue' needs to be 'vue', for linux servers.
you can see the problem here: https://stackblitz.com/edit/github-j7fk9f?file=package.json

Unfortunately this broke on my production server so my system went down, can you adjust this and release a release? thank you very much in advance.

**Comment by bastidest** [comment]
Hi,
thank you for the report, sorry for the slow response. Fixed in https://github.com/bastidest/vue-step-progress/commit/d4627c5
Fixed in Release v1.0.2.
